services:
  app:
    build: 
      context: ..
    container_name: anonymizer
    command: uvicorn demo.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ../latest_model:/app/latest_model 
    environment:
      - PYTHONUNBUFFERED=1
