model:
  model: test_model
  tokenizer: test_model
  dataset_folder: dataset
  exclude_file: null
  entities:
  - working_type
  intents:
  - anonymizing
  - normal
  device: cpu
  synonym: {}
training:
  train_range: 0.95
  num_train_epochs: 10
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: logs/
  early_stopping_patience: 10
  early_stopping_threshold: 0.0001
  output_dir: results/
util:
  intent_threshold: 0.7
  entities_threshold: 0.5
  ambiguous_threshold: 0.2
