model:
  model: sentence-transformers/LaBSE
  tokenizer: sentence-transformers/LaBSE
  dataset_folder: dataset
  exclude_file: null
  entities:
  - userpass
  - email
  - date
  - amount
  - name
  - national_id
  - card_number
  - account_number
  - iban
  - request_number
  - track_number
  - postal_code
  intents:
  - anonymizing
  - normal
  device: cuda
  synonym: {}
training:
  train_range: 0.95
  num_train_epochs: 10
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: logs/
  early_stopping_patience: 10
  early_stopping_threshold: 0.0001
  output_dir: results/
util:
  intent_threshold: 0.7
  entities_threshold: 0.5
  ambiguous_threshold: 0.2
